language: ruby
rvm:
 - 2.2.4
 - 2.3.0
 - jruby-9.0.4.0
 - jruby-9.1.5.0
 - jruby-head
services:
 - rabbitmq
sudo: false
cache: bundler
matrix:
  allow_failures:
    - rvm: jruby-head
branches:
  only:
  - master
