language: ruby
os:
  linux
dist:
  trusty
rvm:
 - 2.2.6
 - 2.3.3
 - jruby-9.0.5.0
 - jruby-9.1.7.0
 - jruby-9.1.12.0
 - jruby-head
services:
 - rabbitmq
sudo: false
cache: bundler
matrix:
  allow_failures:
    - rvm: jruby-head
branches:
  only:
  - master
