language: ruby
os:
  linux
dist:
  trusty
rvm:
 - 2.3.8
 - 2.5.7
 - jruby-9.1.12.0
 - jruby-9.2.7.0
 - jruby-head
services:
 - rabbitmq
sudo: false
cache: bundler
matrix:
  allow_failures:
    - rvm: jruby-head
branches:
  only:
  - master
